### ISSUE TITLE
Font size and window width

### ISSUE THREAD

**Issue by tflo** [Ny0n/Nys_ToDoList#13]
Discovered your add-on just yesterday, and love it so far! (Until now I managed my ToDos in [TinyPad](https://www.wowinterface.com/downloads/info4417-TinyPad.html).)

However, I came across a weird design issue:

I thought, I add a fourth and maybe fifth tab, but I quickly noticed that the font size becomes ridiculously large when I increase the window width to anything wider than 3 tabs. (I know, I can leave it at 3-tabs width, and then the additional tabs go into a submenu. While still better than having a huge font, this is a bit clunky to access.)

So, my suggestion (possibly I’m blind and an option is already somewhere):

Decouple the font size from the window width! Add a simple font size setting to the add-on settings. The size I set there (eg 12pt) should remain as set, no matter the window width.

(If you really love that _window-width-changes-font-size_ feature, you could still keep it in, for example via shift-dragging the window corner.)

Thanks in advance for considering,
and thanks for this very nice add-on!

– Tom

**Comment by Ny0n** [comment]
Hey Tom!

What you are suggesting is a very nice idea, this font size thing was an issue for me for a long time because of the max length the items and categories name can have.

I thought that if we resized the window to make it bigger and suddenly found that everything was stuck to the left and couldn’t go further, it would seem weird, so i kept it the way you call window-width-changes-font-size, but now that someone finally comments on this, i’ll see what i can do to make it better 😅 probably adding a font size setting is the best solution 😉

**Comment by tflo** [comment]
> i’ll see what i can do to make it better 😅 probably adding a font size setting is the best solution 😉

Happy to hear 😍

> suddenly found that everything was stuck to the left and couldn’t go further, it would seem weird

I can imagine this might indeed look a bit weird, but still better than getting smacked in the face by a children’s book-sized font 😵😉

And: 

Once we have a fix, width-independent, font size, you could also increase the max allowed chars per entry. Currently it is a bit restrictive, I often have to add  a “Description” just for a word or two that don’t fit in. (But I understand that you want to avoid multi-line entries.)

Let’s say, I have a 5-tab-wide window (and the font size is fix), then I have enough room for the occasional lengthy entry (eg 60 chars). As a side effect, the window would look less “weird”, since we no more necessarily have a narrow text column at the left and empty space in the rest.

If the user narrows the window, any entry that doesn’t fit in should simply get truncated (marked by an ellipsis). _Ideally,_ a tooltip could show the entire text. (Btw, and independently of the subject of this thread, I would also implement a tooltip that shows the content of the Description field.)

– Tom

**Comment by Ny0n** [comment]
> If the user narrows the window, any entry that doesn’t fit in should simply get truncated (marked by an ellipsis).

Oh right, could have done that :D

>  (But I understand that you want to avoid multi-line entries.)

Actually I kind of forgot about this as I had other things to do at the time and this specific feature seemed like too much of a hassle. But now I might actually be able to implement it, something like a soft wrap (instead of using an ellipsis), and this would completely remove the need to limit the number of allowed chars per entry!

Well then seems like I have some work to do, adding a font size, removing the entry size limit, adding multi-line entries / soft-wrap and a tooltip for the description. This won't come all at once, but you should see those features in the near future 😉

Thanks for the suggestions!

**Comment by tflo** [comment]
> This won't come all at once, but you should see those features in the near future

As mentioned, I discovered your add-on only very recently. So, for me, these little design flaws are really negligible compared to not knowing/using your add-on at all 😉. Looking forward to your changes, whenever you find the time 😊.

**Comment by tflo** [comment]
Thank you for the added description tooltip in v6.1. Really appreciated!

**Comment by tflo** [comment]
OMG, the ugly font bug is fixed :-)

(Calling it 'bug' but I know it was _sort of_ WaD ;)

Some time after this post, I switched to [Executive Assistant](https://www.curseforge.com/wow/addons/exec_assist), not only because of the font bug, but also because it's much easier to handle when you have an army of alts (separate profiles don't help much here). 

_Example:_

My AH toon sold a level 25 Chrominius. A lookup in BagSync shows me that she has 1 more L25 in her bank, and that there is 1 more L25 in alt XYZ's bank, and 4 more L1 in alt JKL's bank. 

So I take the one from the bank, and then in Executive Assistant I can easily create tasks via the chat console, e.g. `/eac >xyz 1 chrom to AH1` and `/eac >jkl 1 chrom to queue`, which I only see when I'm on alts XYZ or JKL, and which reminds me to send 1 Chrominius to toon AH1 (when I'm on XYZ) or to add 1 Chrominius to Rematch's leveling queue (when I'm on toon JKL). _Without cluttering up other toons' or global tasks, and without having to switch profiles._

But I've noticed that Nys has improved in that department too, with global and profile tabs now. Must investigate this... :)

**Comment by Ny0n** [comment]
Hey there! yeah finally 😅

Executive Assistant can indeed do a LOT of things, but I always found it too complicated and if we just want to quickly setup a simple list, it's a bit of a hassle.

That's why I created my own addon and then later started to publish it, but the core principle has always been to keep it as simple and as easy to use as possible (e.g. we can do a lot directly from inside the list, and some people won't even need to ever go into the addon options).

Even though it can be upgraded, I don't think Nys will ever go that far in terms of handling alts armies, or check things in bags, or whatever. And I respect those who need more power / features 😉

And btw thanks for your font suggestions, it really was some things that needed to be done 👀

**Comment by tflo** [comment]
> And btw thanks for your font suggestions, it really was something that needed to be done 👀

Np ;)

>Executive Assistant can indeed do a LOT of things, but I always found it too complicated and if we just want to quickly setup a simple list, it's a bit of a hassle.

That was my first impression when I first touched the addon. But it quickly turned out that for me (and probably for anyone who has more than a couple of alts) the way EA is structured is so much better - and simpler - than anything else.

See my example above. Basically, the point is to have everything in one profile, but also to be able to apply attributes to tasks that decide which toon the task is visible to, or when, or if it is account wide, etc.

Maybe it would be possible to duplicate this with Nys, but I would have to use pseudo-tags for my toons (i.e. hardcoded prefixes or something), and I would have to do a lot of copying and pasting of tasks every time I wanted to add new ones.



But, as I said, I have not yet played with the apparently new Toon vs. Global Profile feature of Nys.

**Comment by tflo** [comment]
Oh, and…

> I don't think Nys will ever go that far in terms of handling alts armies, or _check things in bags_, or whatever.

…I only mentioned BagSync because in my example it is part of the workflow and a prerequisite for sending tasks to the correct toons. My intention was _not_ to say that Nys should have inventory features, for the same reason that Nys should _not_ have features like quest completion checking (as I've seen people asking for): There are already more than enough – and very good – addons that do that.

**Comment by Ny0n** [comment]
Yea dw I know you didn’t mean it like that, just wanted to explain what were my goals for Nys.

Addons that already do specific things well will often be better than other addons trying to do a bit of everything, and that’s why it’s not my intention to do so 😉

**Comment by tflo** [comment]
> Addons that already do specific things well will often be better than other addons trying to do a bit of everything

Exactly :-) As someone said: [Write programs that do one thing and do it well.](https://klarasystems.com/articles/unix-philosophy-a-quick-look-at-the-ideas-that-made-unix/)
