### ISSUE TITLE
To-do list window not showing in UI or options

### ISSUE THREAD

**Issue by joanofarcana** [Ny0n/Nys_ToDoList#22]
Hello,

I recently updated, and I'm having issues. The to-do list window is not showing, I can't toggle it with a chat command or a key-binding and the add-on options in the Blizzard UI only show settings for TDL Backup. The weird thing is, I can do some commands and receive the chat messages. I've tried disabling all add-ons but TDL, reinstalling from CurseForge, deleting from CurseForge and then reinstalling, removing the folders from the Addon folder manually and reinstalling from GitHub.

Any ideas?

**Comment by joanofarcana** [comment]
Oop, I fixed it! Manually changed the current version in the SavedVariables lua file to 7.1 (last version I used was 6.5.1 apparently) and everything seems to be loading okay. I don't know just enough code to make changes, but not enough to know if I've irrevocably broken everything, so please let me know if there's anything I need to look out for.

**Comment by Ny0n** [comment]
Okay nvm I think I got it, it was my bad because I did not account for people that updated to 7.0+ from older addon versions than  6.6... it has to do with the new tutorial system. Doing what you did to the SavedVariables file is one fix, basically you just precisely skipped the error part, so you should be good. I'm still going to publish an update that fixes this problem. Sorry for the trouble!
