### ISSUE TITLE
Bug window opacity

### ISSUE THREAD

**Issue by Faycop** [Ny0n/Nys_ToDoList#26]
Hello, I have two wow accounts that have the same settings in the WTF folder, on the first wow account I have this weird bug that seems like the background has a superior strata, different from the content.

Attached the weird bug
![todo-bug](https://github.com/Ny0n/Nys_ToDoList/assets/1913375/3a2c7f90-10c7-4945-a0a8-59864ea10836)
![todo-bug-ok](https://github.com/Ny0n/Nys_ToDoList/assets/1913375/cea4746e-49c0-40d3-bf12-9c76229770d5)

**Comment by Ny0n** [comment]
Yo! Huh, weird. Are you still able to click on the buttons and items in this state ?

I'll take a look a it tomorrow and let you know if I find a fix 😉

**Comment by Ny0n** [comment]
Soo kinda weird bug, I'm not sure if I found a fix or not because I can't really replicate it without changing the code, so I'll attach to this comment a version of the addon with maybe a fix?
[Nys_ToDoList_maybe_fix.zip](https://github.com/Ny0n/Nys_ToDoList/files/12641543/Nys_ToDoList_maybe_fix.zip)

If doing this doesn't work, try running this line of code in your chat window and tell me if it fixes the problem or not.
`/run local f = NysTDL.mainFrame:GetFrame().ScrollFrame f:SetFrameLevel(f:GetParent():GetFrameLevel()+1)`

If none of this works, please send me your saved variables file for the Nys_ToDoList_Backup addon (Nys_ToDoList_Backup.lua), so that I can see if it's caused by something broken in your saved infos. Sorry for the troubles.

**Comment by Faycop** [comment]
Hey man thanks for the awesome support :)

Sadly both the addon_maybe_fix and the /run command did not work. Attached my WTF folder with the saved variables for every 3 account:
[nys-todolist-wtf.zip](https://github.com/Ny0n/Nys_ToDoList/files/12646471/nys-todolist-wtf.zip)

**Comment by Ny0n** [comment]
No problem, thanks for the files, I'll check those when I can.

Also, in the meantime, can you tell me if the bug still happens when all of your other addons are disabled ? Just to make sure whether it is due to a conflict or not.

**Comment by Faycop** [comment]
Hey man you were absolutely right! The bug was caused by this other addon:

[](https://www.curseforge.com/wow/addons/copypasta)

Are you able to fix anyway? I really like copypasta, but I use your addon more often, so if you say you can do nothing I'll just delete Copypasta :)

**Comment by Ny0n** [comment]
So it is! I'll try to find a fix this week, I'll let you know if I find anything.

**Comment by Ny0n** [comment]
So the bug is due to a library, not copypasta in itself. The library's name is LibStrataFix and it's a pretty weird bug that I'm gonna have to fix by updating my addon.

In the meantime, you can fix the bug and still use CopyPasta by going into the CopyPasta/embeds.xml file and removing that line: `<Include file="libs\LibStrataFix\lib.xml"/>`.

I apologize for the delay, haven't had much time to work on this recently. Anyways, thanks for the bug report!

**Comment by Faycop** [comment]
Thanks a lot for the effort! :)
No apologies, you'll fix it when you can, absolutely no worries :D
